CRMproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('crmapp.urls','crmapp'),namespace='crmapp')),
    path('customerapp/',include(('customerapp.customerappurls','customerapp'),namespace='customerapp')),
    path('adminapp/',include(('adminapp.adminappurls','adminapp'),namespace='adminapp')),

]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crmapp/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.index,name='index'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('registration/',views.registration,name='registration'),
    path('login/',views.login,name='login'),
    path('contactus/',views.contactus,name='contactus'),
]

crmapp/models.py
from django.db import models

# Create your models here.
class Enquiry(models.Model):
    id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    contactno=models.CharField(max_length=10)
    emailaddress=models.EmailField(max_length=100)
    subject=models.CharField(max_length=500)
    message=models.CharField(max_length=5000)
    posteddate=models.CharField(max_length=30)
class Customer(models.Model):
    name=models.CharField(max_length=50)
    gender=models.CharField(max_length=6)
    address=models.CharField(max_length=500)
    contactno=models.CharField(max_length=10)
    emailaddress=models.EmailField(max_length=100,primary_key=True)
    regdate=models.CharField(max_length=30)
class Login(models.Model):
    userid=models.CharField(max_length=100, primary_key=True)
    password=models.CharField(max_length=30)
    usertype=models.CharField(max_length=30)
    

crmapp/views.py
from django.shortcuts import render,redirect, reverse
import datetime
from . models import Enquiry,Customer,Login
from django.core.exceptions import ObjectDoesNotExist
from . smssender import sendsms
# Create your views here.
def index(request):
    return render(request,"index.html")
def aboutus(request):
    return render(request,"aboutus.html")
def registration(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        contactno = request.POST['contactno']
        gender = request.POST['gender']
        address = request.POST['address']
        password = request.POST['password']
        conpassword = request.POST['conpassword']
        regdate = datetime.datetime.today()
        usertype = 'customer'
        if password == conpassword:
            cust=Customer(name=name,gender=gender,address=address, emailaddress=email, contactno=contactno, regdate=regdate)
            cust.save()
            valid=Login(userid=email, password=password, usertype=usertype)
            valid.save()
            return render(request, 'registration.html',{'msg':"Registration Success"})
        else:
            return render(request,"registration.html",{'msg':'Password not matched'})
    return render(request,"registration.html")
def login(request):
    if request.method=="POST":
        userid=request.POST['userid']
        password=request.POST['password']
        try:
            obj=Login.objects.get(userid=userid, password=password)
            if obj is not None:
                if obj.usertype=="customer":
                    request.session["userid"]=userid
                    return redirect(reverse("customerapp:customerhome"))
                elif obj.usertype=="admin":
                    request.session["adminid"]=userid
                    return redirect(reverse("adminapp:adminhome"))
        except ObjectDoesNotExist:
                msg="Invalid User"
                return render(request,"login.html",{"msg":msg})
    return render(request,"login.html")
def contactus(request):
    if request.method == "POST":
        name = request.POST['name']
        contactno = request.POST['contactno']
        emailaddress = request.POST['emailaddress']
        subject = request.POST['subject']
        message = request.POST['message']
        posteddate = datetime.datetime.today()
        enq = Enquiry(name=name,contactno=contactno,emailaddress=emailaddress,subject=subject,message=message,posteddate=posteddate)
        enq.save()
        sendsms(contactno)
        return render(request,"contactus.html",{"msg":"Enquiry is saved"})

    return render(request,"contactus.html")

crmapp/templates/aboutus.html
{% extends "parent.html" %}
{% block main %}
<!--<h2 style="text-align:center;"> This is Index page</h2>-->
<h2 style="text-align: center; margin-top: 30px;">About Us</h2>
<div class="row" style="">
    <div class="col-sm-3"></div>
    <div class="col-sm-6" style="text-align: center;">
        <p style=" text-align: justify;">We are here to provide you best tretment and facilities with expereinced Doctors and Our tested reports with 100% accuracy Lorem ipsum dolor sit amet consectetur adipisicing elit. Iusto, ad? </p>
    </div>
    <div class="col-sm-3"></div>

</div>
<div class="row mt-2" style="">
    <div class="col-sm-6">
        <h2 style="text-align: center; ">Our Services</h2>
        <p style=" text-align: justify;">Surgical services include anesthesiology services, nursing care, pre- and post-operative rooms, and lab and x-ray technicians. Hospitals provide pharmacy services that supply patients with medications as prescribed</p>
    </div>
    <div class="col-sm-6">
        <h2 style="text-align: center;">Products & Facilities</h2>
        <p style=" text-align: justify;">Nebulizers, CPAP, BiPAP, ventilators are always on their medical equipment list. In the present crisis caused by the second wave of coronavirus infection across the country, many hospitals are dealing with a shortage of ventilators and other respiratory devices.</p>
    </div>
</div>
<div class="row" style="">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <h2 style="text-align: center;">Experienced Doctor</h2>
        <p style="text-align: justify;">A doctor's profile primarily includes the professional details about the doctor, such as their qualifications, experience, services and contact details. Doctors usually create their profiles on their personal sites or websites that allow doctors to list themselves.</p>
    </div>
    <div class="col-sm-2"></div>
</div>
{% endblock main %}

crmapp/templates/contactus.html
{% extends "parent.html" %}
{% block main %}
<h2 style="text-align:center;"> Enquiry Form</h2>
{% if msg %}
  <p style="color:green; text-align:center;">{{msg}}</p>
{% endif %}
<form class="form-group" method="post">
{% csrf_token %}
    <table class="table" style="width:90%;margin:auto">
    <tr>
        <td>Enter name</td>
        <td>
            <input type="text" name="name" placeholder="Enter name" class="form-control"/>
        </td>

    </tr>
    <tr>
        <td>Enter contact No</td>
        <td>
            <input type="text" name="contactno" placeholder="Enter contact No" class="form-control"/>
        </td>
    </tr>
    <tr>
        <td>Enter Email Address</td>
        <td>
            <input type="email" name="emailaddress" placeholder="Enter Emmailaddress" class="form-control"/>
        
        </td>
    </tr>
    <tr>
        <td>Enter Subject</td>
        <td> 
            <input type="text" name="subject" placeholder="Enter Subject" class="form-control"/>
        </td>
    </tr>
    <tr>
        <td>Enter Message</td>
        <td> 
            <textarea name="message" class="form-control"></textarea>
        </td>
    </tr>
    <tr>
        <td></td>
        <td colspan="2">
            <button type="submit" class="btn btn-primary" style="margin:auto;">Submit</button>
        
        </td>
        
    </tr>
    </table>
</form>
{% endblock main %}

crmapp/templates/index.html
{% extends "parent.html" %}
{% block main %}
<!-- <h2 style="text-align:center;"> This is Index page</h2> -->
<div class="row" style="height: 100%;  background-image: radial-gradient(at top left, transparent 67%, #f3f3f3 67.5%),
linear-gradient(135deg, rgb(71, 164, 174) 0%, rgb(132, 2, 2) 100%);
background-size: 120% 100%,cover;
background-repeat: no-repeat;
margin: 0;
height: 100vh; background-size: cover; width: 103%; ">
    <div class="col-sm-8" style="height: 100%; width: 60%;">
        <div id="home" style="margin-top: 140px; margin-left: 10px; padding: 15px;">

            <span style="font-size: 30px; font-weight: bold; line-height: 30px;text-align: center; color: yellow;">MEDICAL <br>HELTHCARE</span>
            <p style="text-align: justify; margin-top: 20px; font-size: 18px; color:rgb(255, 255, 255);">Health care, or healthcare, is the improvement of health via the prevention, diagnosis, treatment, amelioration or cure of disease, illness, injury, and other physical and mental impairments in people. Health care is delivered by health professionals and allied health fields. Medicine, dentistry, pharmacy, midwifery, nursing, optometry, audiology, psychology, occupational therapy, physical therapy, athletic training, and other health professions all constitute health care.</p>
            <a href="#"><button type="submit" class="btn btn-primary">Read More..</button></a>
        </div>
    </div>
    <div class="col-sm-4" style="height: 100%; width: 40%;">
        <div class="imgsh">
            <img src="static/images/d1.png" style="height: 70%; width: 90%; margin-top: 80px;" alt="doctor image">
        </div>
    </div>
</div>
{% endblock main %}

crmapp/templates/login.html
{% extends "parent.html" %}
{% block main %}
<script>
    function validate()
    {
      var userid=document.getElementById("userid");
      var password=document.getElementById("password");
      if(userid.value=="" || userid.value==null)
      {
         alert("Please enter user id");
         userid.focus();
      }
      else if(password.value=="" || password.value==null)
      {

         alert("Please enter password");
         password.focus();
      }
      else
      {
        document.getElementById("frmlogin").submit();
      }

    }
</script>
<h2 style="text-align: center;">Login Form</h2>
{% if msg %}
   <p style="text-align: center;">{{msg}}</p>
{% endif %}
<form  method="POST" class="form-group" id="frmlogin" onsubmit="event.preventDefault();validate();">
    {% csrf_token %}
    <table class="table" style=" margin: auto; width: 90%;">
    <tr>
        <td>Enter user Id</td>
        <td>
            <input type="text" id="userid" name="userid" class="form-control" palceholder="User Id" />
        </td>
    </tr>
    <tr>
        <td>Enter Password</td>
        <td>
            <input type="password" id="password" name="password" class="form-control" placeholder="Passwword"/>
        </td>
    </tr>
    <tr>
        <td></td>
        <td>
            <button type="submit" class="btn btn-primary">Login</button>
        </td>
    </tr>


    </table>
</form>


{% endblock main %}

crmapp/templates/parent.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CRM</title>
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" />

</head>

<body>
  <div class="container">
    <div class="row bg-danger text-light text-center">
      <div class="col-sm-4">Contact us:+919918289014</div>
      <div class="col-sm-4">Email: ajeetsofra@gmail.com</div>
      <div class="col-sm-4"> follow Us: Linkedin</div>

    </div>
    <div class="menu">
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'crmapp:index' %}">
            <img src="{% static 'images/logo.jpg' %}" width="50" height="50" />
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'crmapp:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'crmapp:aboutus' %}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'crmapp:registration' %}">Registration</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'crmapp:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'crmapp:contactus' %}">Contact Us</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>



    </div>
    <div class="row mt-2">
      <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'images/image1.jpg'%}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/image2.jpg'%}" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="{% static 'images/image3.jpg'%}" class="d-block w-100" alt="...">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-sm-4" style="background-color: #bdffff; min-height: 600px;">
        <h5 align="center" style="margin-top: 10px; color: red;">Our Purpose!</h5>
        <p style=" text-align: justify;">Our humanitarian approach for healthcare in pursuit of our purpose ‘Caring for Life’ makes us a partner of
          choice for global health bodies and stakeholders.</p>
        <h5 align="center" style=" color: red;">Illness To Wellness!</h5>
        <p style=" text-align: justify;">We are actively working towards delivering innovative solutions and supporting patients across the healthcare
        continuum enabling a shift from illness to wellness. We are continuously striving to stay ahead and contribute
        to the ongoing need for quality healthcare.</p>
        <h5 align="center" style=" color: red;">Our People. Our Pride.!</h5>
        <p style=" text-align: justify;">We recognize that our employees are the cornerstone of our success and integral to meeting our long-term business success goals. We are committed to investing in our people, providing them with opportunities and an enabling environment to thrive.</p>
      </div>
      <div class="col-sm-8" style="background-color: whitesmoke;min-height: 600px;">
        {% block main %}
        {% endblock main %}
      </div>
    </div>
    <div class="row mt-2">
      <div class="col-sm-6" style=" background-color: black;color: white;text-align: center;font-size: 30px;">
        Copright &copy; TO MARC Lab </div>

      <div class="col-sm-6" style=" background-color: navy;color: white;text-align: center;font-size: 30px;">
        Developed By :- Ajeet Chaurasiya </div>


    </div>

  </div>

  </div>

  <script src="{%static 'js/bootstrap.bundle.js' %}"></script>
  <script src="{%static 'js/script.js' %}"></script>
</body>

</html>

crmapp/templates/registration.html
{% extends "parent.html" %}
{% block main %}
<h2 align="center">User Registration form</h2>
{%if msg%}
<p class="text-danger p-2 text-center">{{msg}}</p>
{% endif %}
<form action="{% url 'crmapp:registration' %}" method="post" class="from-group mt-3">
    {%csrf_token%}
    <table class="table" style="margin: auto; width: 90%;">
        <tr>
            <td>Enter Name</td>
            <td><input type="text" class="form-control"   name="name" id=""></td>
        </tr>
        <tr>
            <td>Select Gender</td>
            <td>
                <input type="radio" class="ms-3" value="male"   name="gender" id="">Male
                <input type="radio" class="ms-3" value="female"  name="gender" id="">Female
            </td>
        </tr>
        <tr>
            <td>Enter Address</td>
            <td>
                <textarea  id="" class="form-control" name="address"  cols="30" rows="3"></textarea>
            </td>
        </tr>
        <tr>
            <td>Enter contact</td>
            <td><input type="number" class="form-control"   name="contactno" id=""></td>
        </tr>
        <tr>
            <td>Enter Email</td>
            <td>
                <input type="email" class="form-control"   name="email" id="email">
            </td>
            <td><span id="sp5"></span></td>
        </tr>
        <tr>
            <td>Enter Password</td>
            <td><input type="password"  class="form-control"  name="password" id=""></td>
        </tr>
        <tr>
            <td>Confirm Password</td>
            <td><input type="password" class="form-control"   name="conpassword" id=""></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" name="register" class="form-control bg-success" onsubmit="eml()"  style="width: 50%;"  value="Register" id="">
            </td>
        </tr>
    </table>
</form>
{% endblock main %}